<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert([
            [
                'name'=>'Audible',
                'logo'=>'audible.jpg',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Video',
                'logo'=>'video.jpg',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Software',
                'logo'=>'computer.png',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Hardware',
                'logo'=>'hardware.png',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Computer science',
                'logo'=>'computer.webp',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'High-Tech & Gadget',
                'logo'=>'high-tech.jpg',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Musical instrument',
                'logo'=>'music-instrument.jpg',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Electronic',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Stationery',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Scripture',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Game & Toy',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Clothing',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Beauty',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Hair',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'crockery and cutlery',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Kitchen',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Home appliance',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Home',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Cleaning product',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Toiletry',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Desktop',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Computer component',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Furnishing',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Gardening & field',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Makeup',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Bag',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Jewelry',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Sport',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Transport',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Automobile',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Urban sliding',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Garage',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Grocery',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Food',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Photgraphy',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Device',
                'logo'=>null,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
        ]);
    }
}
