<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductDetailNameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product_detail_names')->insert([
            [
                'name'=>'author',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'format',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'file_size',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'page_number',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'language',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'editor',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'book_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'platform',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'phone_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'color',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'production_country',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'brand',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'modele',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'max_extensible_support',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'battery_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'operating_system',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'central_processing_unit',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'graphics_processing_unit',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'sim_card',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'screen_size',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'touch',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'resolution',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'processor_chipset',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'front_camera',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'rear_camera',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'battery',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'accessory',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'network',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'bluetooth',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'sensor',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'weight',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'height',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'width',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'depth',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'main_material',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'computer_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'screen_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'processor_brand',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'processor_speed',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'processor_socket',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'number_core',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'number_thread',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'generation',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'graphic_chipset_brand',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'keyboard',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'speaker',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'ram_memory_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'ram_memory_size',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'ram_memory_max_size',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'rom_memory_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'rom_memory_size',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_usb_2.0',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_usb_3.0',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_usb_3.1',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_hdmi',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_vga',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_firewire',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_wifi',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_bluetooth',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'connectivity_port',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_number_button',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'scroll_wheel',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_connection_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_wireless_technology_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_cable_length',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_sensor_resolution',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_sensor_tehnology',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_power_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_battery_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'mouse_battery_life',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'motherboard_frequency',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'motherboard_chipset_type',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],

        ]);
    }
}
