<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sub_categories')->insert([
            [
                'name'=>'Book',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Movie',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'TV series',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Video game',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Phone & Tablet',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Console',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Laptop',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Desktop',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Mouse',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Motherboard',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Keyboard',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Scanner',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Printer',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Storage device',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Microcontroller',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Resistance',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'notebook',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Agenda',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Pen',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Pencil',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Eraser',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Shoe',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Bike',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'plush',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Figurine',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Clothing',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Soap',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'shampoo',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Laundry',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Lye',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'stove',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Refrigerator',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Blender',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Carpet',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Armchairs',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Chairs',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Curtains',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Watering can',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Leaf vacuum cleaner',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Wheelbarrow',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Fork',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Pickaxe',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Rake',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Shovel',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Lawn mower',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Saw',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Plant',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Swimming pools',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Spas',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Chain saw',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Perfume',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Hairstyle',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Backpack',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Hand bag',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'suitcase',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Ring',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Headband',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Barette',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Jewelry',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Jewelry button',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Earring',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Bracelet',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Chain',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Signet ring',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'heart jewelry',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Crowned',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Tiara',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Medallion',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Watches',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Pendant',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'balls',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Scooters',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Oil and Fluids',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Steering wheel cover',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Glass sun visor',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Automotive shampoos',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Aromatic herb',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Oil',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Pasta & noodle',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Confectionery & chocolate',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'spice & aroma',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Snack',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Jams',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Guitar',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Piano',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Camera & Camcorder',
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'Headphone',
                'created_at'=>now(),
                'updated_at'=>now(),
            ]
        ]);
    }
}
